### ISSUE TITLE
running this code on windows ，the following error occurred

### ISSUE THREAD

**Issue by xupinggl** [tomeramit/SegDiff#6]
![1683377577315](https://user-images.githubusercontent.com/102807353/236625354-9bd3ca93-f8f1-4cd5-94e9-2adf1d64a5d3.png)

**Comment by xupinggl** [comment]
after modify dist_util.py line 29 backend = "gloo"

**Comment by 170744039** [comment]
在 dist.broadcast（）上面加入  p=p+0

**Comment by xupinggl** [comment]
您好，您的邮件我已收到，我会尽快回复的，谢谢！

**Comment by tomeramit** [comment]
I have never attempted to launch the framework on Windows. If you are able to do so successfully, I would welcome you to open a pull request for it :)

**Comment by xupinggl** [comment]
@170744039 The problem has been solved,thanks!

**Comment by 170744039** [comment]
可以加个联系交流一下吗？我也在复现这个，能跑是能跑，但没有结果。我的QQ2978064409
