### ISSUE TITLE
When I train, I will encounter the problem of 'lg_loss_scale' continuously decreasing, even if it is already less than 0

### ISSUE THREAD

**Issue by 810238492** [tomeramit/SegDiff#7]
When I train, I will encounter the problem of 'lg_loss_scale' continuously decreasing, even if it is already less than 0

**Comment by tomeramit** [comment]
On which dataset you train?

**Comment by 810238492** [comment]
> 

On my own dataset, grassland related

**Comment by tomeramit** [comment]
I know I sometimes encounter this when my data wasn't normalized, so maybe it's related?
you can also try to use flag --learn_sigma True, it may help as well

**Comment by 810238492** [comment]
> I know I sometimes encounter this when my data wasn't normalized, so maybe it's related? you can also try to use flag --learn_sigma True, it may help as well

Thank you for your answer. I will give it a try

**Comment by tomeramit** [comment]
ok, I'm closing the issue (hope it resolved) if not feel free to reopen it
